spring.application.name=api-gateway
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:change-this-secret-to-a-secure-value}

auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
users.service.url=${USERS_SERVICE_URL:http://localhost:8087}
report.service.url=${REPORT_SERVICE_URL:http://localhost:8082}
support.service.url=${SUPPORT_SERVICE_URL:http://localhost:8083}
ai.service.url=${AI_SERVICE_URL:http://localhost:8084}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8085}
analytics.service.url=${ANALYTICS_SERVICE_URL:http://localhost:8086}
